name: Deploy Holaplex Storefront

on:
  push:
    branches: [master]

defaults:
  run:
    working-directory: js

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: yarn
      - run: yarn build
        env:
          CI: "false"
          NEXT_PUBLIC_ARWEAVE_URL: ${{ secrets.NEXT_PUBLIC_ARWEAVE_URL }}
      - uses: aws-actions/configure-aws-credentials@v1
        working-directory: js/packages/web
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: |
          yarn run deploy:s3 s3://${{ secrets.S3_BUCKET }}/
      - run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html"
